#!/usr/bin/env python

import cmd
import re
import readline
import subprocess

class Igita(cmd.Cmd):
    prompt = "igita >> "
    
    git_cmds = [
        'add',
        'archive',
        'branch',
        'cat-file',
        'checkout',
        'clone',
        'commit',
        'config',
        'diff',
        'fetch',
        'fsck',
        'gc',
        'grep',
        'init',
        'instaweb',
        'log',
        'ls-tree',
        'merge',
        'prune',
        'pull',
        'push',
        'remote',
        'reset',
        'rm',
        'show',
        'stash',
        'status',
        'tag',
    ]
    
    hist_file = ''
    FNULL = ''
    
    def cmd(self, cmd, line, **kwargs):
        params = self.params(cmd, line)
        return subprocess.call(
            params,
            stdout=kwargs.get('stdout', None),
            stderr=kwargs.get('stderr', None),
        )
    
    def cmd_output(self, cmd, line, **kwargs):
        params = self.params(cmd, line)
        return subprocess.check_output(
            params,
            stderr=kwargs.get('stderr', None),
        )
        
    def params(self, cmd, line):
        params = []
        
        if cmd:
            params.append(cmd)
        
        for i, x in enumerate(re.split('"', line)):
            if i%2:
                param = '"%s"' % x
                params.append(param)
            else:
                for j, y in enumerate(re.split("'", x)):
                    if j%2:
                        param = '"%s"' % y
                        params.append(param)
                    else:
                        for s in y.split():
                            params.append(s)
        return params
    
    def default(self, line):
        self.cmd('git', line)
    
    def do_git(self, line):
        self.default(line)

    def complete_git(self, text, line, begidx, endidx):
        if not text:
            return self.git_cmds
        else:
            return [cmd for cmd in self.git_cmds if cmd.startswith(text) ]

    def do_ls(self, line):
        self.cmd('git', 'status ' + line)
        
    def do_shell(self, line):
        self.cmd("", line)
            
    def do_cd(self, line):
        self.cmd('git', 'checkout ' + line)
    
    def do_quit(self, line):
        readline.write_history_file(self.hist_file)
        quit()
    
    def do_q(self, line):
        self.do_quit(line)

    def do_EOF(self, line):
        print ''
        self.do_quit(line)

    def emptyline(self):
        self.do_ls('')

    def preloop(self):
        self.FNULL = open('/dev/null', 'w')
        if self.cmd('git', 'rev-parse --show-toplevel', stdout=self.FNULL, stderr=self.FNULL):
            print "This does not seem to be a git repository"
            quit()
            
        self.hist_file = self.cmd_output('git', 'rev-parse --show-toplevel').strip()
        self.hist_file += '/.igita_history'
        
        open(self.hist_file, 'a').close()
        readline.set_history_length(1000)
        readline.read_history_file(self.hist_file)
        
if __name__ == '__main__':
    Igita().cmdloop()

